'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.832
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Firefly.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        '''&lt;areas&gt;
        '''	&lt;name area=&quot;34&quot;&gt;
        '''		&lt;group&gt;01&lt;/group&gt;
        '''	&lt;/name&gt;
        '''	&lt;name area=&quot;37&quot;&gt;
        '''		&lt;group&gt;01&lt;/group&gt;
        '''	&lt;/name&gt;
        '''	&lt;name area=&quot;5610&quot;&gt;
        '''		&lt;group&gt;01&lt;/group&gt;
        '''	&lt;/name&gt;
        '''	&lt;name area=&quot;560221&quot;&gt;
        '''		&lt;group&gt;01&lt;/group&gt;
        '''	&lt;/name&gt;
        '''	&lt;name area=&quot;560222&quot;&gt;
        '''		&lt;group&gt;01&lt;/group&gt;
        '''	&lt;/name&gt;
        '''	&lt;name area=&quot;560223&quot;&gt;
        '''		&lt;group&gt;01&lt;/group&gt;
        '''	&lt;/name&gt;
        '''	&lt;name area=&quot;560224&quot;&gt;
        '''		&lt;group&gt;01&lt;/group&gt;
        '''	&lt;/name&gt;
        '''	&lt;name area=&quot;560225&quot;&gt;
        '''		&lt;group&gt;01&lt;/group&gt;
        '''	&lt;/name&gt;
        '''	&lt;name area=&quot;622&quot;&gt;
        '''		&lt;group&gt;01&lt;/group&gt;
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ccn_area_codes() As String
            Get
                Return ResourceManager.GetString("ccn_area_codes", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Pause() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pause", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Play() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Play", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Question() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Question", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Search() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Search", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property securitylogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("securitylogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        '''&lt;areas&gt;
        '''	&lt;name area=&quot;001&quot;&gt;
        '''		&lt;group&gt;04&lt;/group&gt;
        '''	&lt;/name&gt;
        '''	&lt;name area=&quot;002&quot;&gt;
        '''		&lt;group&gt;04&lt;/group&gt;
        '''	&lt;/name&gt;
        '''	&lt;name area=&quot;003&quot;&gt;
        '''		&lt;group&gt;02&lt;/group&gt;
        '''	&lt;/name&gt;
        '''	&lt;name area=&quot;004&quot;&gt;
        '''		&lt;group&gt;06&lt;/group&gt;
        '''	&lt;/name&gt;
        '''	&lt;name area=&quot;005&quot;&gt;
        '''		&lt;group&gt;06&lt;/group&gt;
        '''	&lt;/name&gt;
        '''	&lt;name area=&quot;006&quot;&gt;
        '''		&lt;group&gt;06&lt;/group&gt;
        '''	&lt;/name&gt;
        '''	&lt;name area=&quot;007&quot;&gt;
        '''		&lt;group&gt;06&lt;/group&gt;
        '''	&lt;/name&gt;
        '''	&lt;name area=&quot;008&quot;&gt;
        '''		&lt;group&gt;90&lt;/group&gt;
        '''	&lt;/name&gt;
        '''	&lt;name area=&quot;009&quot;&gt;
        '''		&lt;group&gt;88&lt;/group&gt;
        '''	&lt;/name&gt;
        '''	&lt;name area=&quot;010&quot;&gt;
        '''		&lt;group&gt;90&lt;/g [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ssn_area_codes() As String
            Get
                Return ResourceManager.GetString("ssn_area_codes", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
